INSERT INTO profile_settings (
  id,
  display_name,
  email,
  website_url,
  github_url,
  instagram_url,
  profile_image_url,
  about_text,
  philosophy_text,
  technical_arsenal_json,
  professional_journey_json,
  education_history_json,
  seo_settings_json,
  updated_at
) VALUES (
  'main',
  'My Name',
  'email@domain.tld',
  'https://domain.tld',
  'https://github.com/github',
  'https://www.instagram.com',
  '/profile.jpg',
  'I am a cybersecurity enthusiast and builder.',
  'Build with focus, test with discipline, ship with confidence.',
  '[]',
  '[]',
  '[]',
  '{}',
  strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
)
ON CONFLICT(id) DO UPDATE SET
  display_name = excluded.display_name,
  email = excluded.email,
  website_url = excluded.website_url,
  github_url = excluded.github_url,
  instagram_url = excluded.instagram_url,
  profile_image_url = excluded.profile_image_url,
  about_text = excluded.about_text,
  philosophy_text = excluded.philosophy_text,
  technical_arsenal_json = excluded.technical_arsenal_json,
  professional_journey_json = excluded.professional_journey_json,
  education_history_json = excluded.education_history_json,
  seo_settings_json = excluded.seo_settings_json,
  updated_at = excluded.updated_at;
